#!/bin/bash

SCRIPT_PATH="$( cd "$(dirname "$0")" ; pwd -P )"
SCRIPT_PATH="$(realpath $SCRIPT_PATH)"

[ "${GH_TOKEN}" ] || {
  [ -f $HOME/.private ] && source $HOME/.private
}
[ "${GH_TOKEN}" ] || {
  printf "\nNo Github token set in the environment"
  printf "\nSet GH_TOKEN in $HOME/.private"
  printf "\nExiting\n"
  exit 1
}

PRIV="${SCRIPT_PATH}/src/ubuntu/install/neovim/install_neovim.sh"
[ -f ${PRIV} ] && {
  cp ${PRIV} ${PRIV}-$$
  cat ${PRIV} | sed -e "s/__GITHUB_API_TOKEN__/${GH_TOKEN}/" > /tmp/gh$$
  cp /tmp/gh$$ ${PRIV}
  rm -f /tmp/gh$$
}

sudo docker build -t kasmweb/neovim:dev \
                  -f dockerfile-kasm-ubuntu-jammy-neovim .

[ -f ${PRIV}-$$ ] && mv ${PRIV}-$$ ${PRIV}
